fetch:
	curl -X GET 'https://status.unexpectedeof.casa/?query=simple&service=ON_AIR'

publish:
	wrangler publish

preview:
	wrangler preview --watch

update:
	curl -X POST https://status.unexpectedeof.casa/?service=ON_AIR

